### ISSUE TITLE
Length cannot be less than zero

### ISSUE THREAD

**Issue by GitHubCTS** [nunit/nunitv2#40]
Hi

I am using NUnit GUI Runner to execute my suite developed in Selenium Webdriver C#.Everytime I am getting error as error: Length cannot be less than zero.

If I change the relative path with absolute path then it is working fine. So is there any limitation with Relative Path. Please advise.

NUNIT Version :2.6.4.14350
Framework Version :Net 3.5
Visual Studio 2013

My Code is like this:

String relativePath = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
relativePath = relativePath.Substring(0, relativePath.IndexOf("TestResults"));

So if I change the value for relativePath as "C:\demo\" then it is working fine.

**Comment by CharliePoole** [comment]
Your issue doesn't seem to have anything to do with NUnit. The code is simly using .NET calls to get apath and then find a substring in the path. I can see that you make an assumption about the location of the assembly containing "TestResults" so that will only work if it  really contains that value.
